### ISSUE TITLE
be able to do import

### ISSUE THREAD

**Issue by basz** [dynamsoft-dwt/web-twain-package#2]
Not that this package is available as an NPM package I've noted that including this library via a import statement is not possible due to the fact the initialise and config are merged in the minified version.

https://github.com/dynamsoft-dwt/web-twain-package/blob/master/package.json#L42 is a concatenated version of dynamsoft.webtwain.initialize.js and dynamsoft.webtwain.config.js, but the config version will always previously available configuration...

Therefore doing this will always use the provided configuration.

```
import dwt from 'dwt';
```

I would like to be able to define some global config and then load initialise...

first do this in my app
```
  const Dynamsoft = { WebTwainEnv: {} };

  Dynamsoft.WebTwainEnv.AutoLoad = false;
  // ... more

  window.Dynamsoft = Dynamsoft;
```

Then do

```
import dwt from 'dwt';
```

with *my* settings...

Proposed solution: don't use the minified/concatenated version in package.json main attribute OR set configuration options when they do not exist...

Willing to do a PR if open to such a change..

**Comment by Tom-Dynamsoft** [comment]
@basz Thanks for your comment and sorry that it took so long (2 months?) to get back to you. We've been working from home and some things get neglected.

That said, the dwt library actually doesn't load automatically, when you do 

`import dwt from 'dwt';`

The library sets up the namespace, etc. but stays on hold because we've already set 

`Dynamsoft.WebTwainEnv.AutoLoad = false;`

in the min JS.

Therefore, you should be able to change settings before you do a 'Load' like

`
        Dynamsoft.WebTwainEnv.ProductKey = this.productKey;
        Dynamsoft.WebTwainEnv.Containers = [{ ContainerId: this.containerId, Width: '583px', Height: '513px' }];
        Dynamsoft.WebTwainEnv.Load();
`

Would this work in your case or am I missing something?

**Comment by basz** [comment]
You are correct. And I figured it out eventually. Thanks for getting back to me. Cheers
